 steps:
 # build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/blender-265102/blender-cuda:$COMMIT_SHA', '.']
   timeout: 1200s
 # push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/blender-265102/blender-cuda:$COMMIT_SHA']
 images:
 - 'gcr.io/blender-265102/blender-cuda:$COMMIT_SHA'
